apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account
  name: account
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: account
  type: ClusterIP
status:
  loadBalancer: {}
